/** Render a Report as Markdown (for PR comments / CI artifacts). */

import { CATEGORY_LABELS, type Report } from "../types.js";

const ICON = { error: "✗", warning: "⚠", info: "ℹ", pass: "✓" } as const;

export function toMarkdown(report: Report): string {
  const s = report.summary;
  const out: string[] = [];
  out.push(`# csplint report`);
  out.push("");
  out.push(
    `**${s.score}/100 (${s.grade})** across **${s.policies}** policy(ies) — ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info(s)`,
  );
  out.push("");

  for (const p of report.policies) {
    const ro = p.reportOnly ? " · _Report-Only_" : "";
    out.push(`## ${p.source} — ${p.score}/100 (${p.grade})${ro}`);
    out.push("");
    if (p.findings.length === 0) {
      out.push(`✓ No issues found.`);
      out.push("");
      continue;
    }
    out.push(`| | Category | Directive | Issue | Fix |`);
    out.push(`| - | -------- | --------- | ----- | --- |`);
    for (const f of p.findings) {
      const fix = (f.fix ?? "").split("\n")[0]!.replace(/\|/g, "\\|");
      out.push(
        `| ${ICON[f.severity]} | ${CATEGORY_LABELS[f.category]} | \`${f.directive ?? "—"}\` | ${f.title.replace(/\|/g, "\\|")} | ${fix} |`,
      );
    }
    out.push("");
  }

  out.push(`---`);
  out.push(`<sub>Generated by csplint v${report.version} · ${report.generatedAt}</sub>`);
  out.push("");
  return out.join("\n");
}
